update openstackclient
I stumbled upon problem with
AttributeError: module 'openstack' has no attribute 'version'

then I found out this comes from the openstackclient package https://pypi.org/project/openstackclient/ which was last updated in 2019! this package installs python-openstackclient package, but was not updated for 6 years, so it brings old openstack cli
2. the python-openstackclient package is actually needed https://pypi.org/project/python-openstackclient/ and is the currently actively updated

TLDR: are we sure that we wish to keep on using option 1 from 2019?